-- Seed data for portfolio database
DELETE FROM project_skills;
DELETE FROM project_achievements;
DELETE FROM projects;
DELETE FROM timeline_skills;
DELETE FROM timeline_achievements;
DELETE FROM timeline;
DELETE FROM skills;

-- Insert Skills
INSERT INTO skills (id, name, category) VALUES (1, 'AWS', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (2, 'AWS Amplify', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (3, 'Amazon Bedrock', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (4, 'Amazon Comprehend', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (5, 'Amazon Polly', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (6, 'Amazon Transcribe', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (7, 'Amazon Translate', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (8, 'Atlas', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (9, 'BERT', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (10, 'Biometric Auth', 'Tools');
INSERT INTO skills (id, name, category) VALUES (11, 'Blnk', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (12, 'BullMQ', 'Backend');
INSERT INTO skills (id, name, category) VALUES (13, 'Bun', 'Backend');
INSERT INTO skills (id, name, category) VALUES (14, 'CSS', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (15, 'CSS3', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (16, 'Cloud Pub/Sub', 'Tools');
INSERT INTO skills (id, name, category) VALUES (17, 'Cloud Storage', 'Tools');
INSERT INTO skills (id, name, category) VALUES (18, 'Cloudflare Tunnel', 'Tools');
INSERT INTO skills (id, name, category) VALUES (19, 'Dart', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (20, 'Discord Webhooks', 'Tools');
INSERT INTO skills (id, name, category) VALUES (21, 'Docker', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (22, 'Docker Compose', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (23, 'Drizzle ORM', 'Backend');
INSERT INTO skills (id, name, category) VALUES (24, 'DynamoDB', 'Databases');
INSERT INTO skills (id, name, category) VALUES (25, 'ERP Systems', 'Tools');
INSERT INTO skills (id, name, category) VALUES (26, 'Elysia', 'Backend');
INSERT INTO skills (id, name, category) VALUES (27, 'Express', 'Backend');
INSERT INTO skills (id, name, category) VALUES (28, 'FastAPI', 'Backend');
INSERT INTO skills (id, name, category) VALUES (29, 'Firebase', 'Backend');
INSERT INTO skills (id, name, category) VALUES (30, 'Firebase Genkit', 'Backend');
INSERT INTO skills (id, name, category) VALUES (31, 'Firestore', 'Databases');
INSERT INTO skills (id, name, category) VALUES (32, 'Flutter', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (33, 'Framer Motion', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (34, 'GCP', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (35, 'GLM-OCR', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (36, 'GORM', 'Backend');
INSERT INTO skills (id, name, category) VALUES (37, 'GSAP', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (38, 'Gemini', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (39, 'Git', 'Tools');
INSERT INTO skills (id, name, category) VALUES (40, 'GitHub Actions', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (41, 'Go', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (42, 'Google Cloud', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (43, 'HTML', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (44, 'HTML5', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (45, 'Hardhat', 'Tools');
INSERT INTO skills (id, name, category) VALUES (46, 'Hono.js', 'Backend');
INSERT INTO skills (id, name, category) VALUES (47, 'Hugging Face Transformers', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (48, 'ILMU-GLM-5.1', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (49, 'Java', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (50, 'JavaScript', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (51, 'Jetpack Compose', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (52, 'Jira', 'Tools');
INSERT INTO skills (id, name, category) VALUES (53, 'Keycloak', 'Backend');
INSERT INTO skills (id, name, category) VALUES (54, 'Kotlin', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (55, 'Leaflet', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (56, 'ML Kit OCR', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (57, 'MySQL', 'Databases');
INSERT INTO skills (id, name, category) VALUES (58, 'Next.js', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (59, 'OAuth', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (60, 'ORPC', 'Backend');
INSERT INTO skills (id, name, category) VALUES (61, 'Oasis ROFL', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (62, 'Obsidian', 'Tools');
INSERT INTO skills (id, name, category) VALUES (63, 'Ollama', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (64, 'PHP', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (65, 'PostGIS', 'Databases');
INSERT INTO skills (id, name, category) VALUES (66, 'PostgreSQL', 'Databases');
INSERT INTO skills (id, name, category) VALUES (67, 'Prisma', 'Backend');
INSERT INTO skills (id, name, category) VALUES (68, 'PyTorch', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (69, 'Python', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (70, 'R Programming', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (71, 'React', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (72, 'Redis', 'Databases');
INSERT INTO skills (id, name, category) VALUES (73, 'Redux Toolkit', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (74, 'Room', 'Databases');
INSERT INTO skills (id, name, category) VALUES (75, 'SQLCipher', 'Databases');
INSERT INTO skills (id, name, category) VALUES (76, 'Solidity', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (77, 'Stripe', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (78, 'Sui SDK', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (79, 'TRON', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (80, 'Tailwind CSS', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (81, 'TanStack Query', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (82, 'TanStack Start', 'Frontend');
INSERT INTO skills (id, name, category) VALUES (83, 'Telegram Bot', 'Tools');
INSERT INTO skills (id, name, category) VALUES (84, 'The Graph', 'Tools');
INSERT INTO skills (id, name, category) VALUES (85, 'Turborepo', 'Tools');
INSERT INTO skills (id, name, category) VALUES (86, 'TypeScript', 'Programming Languages');
INSERT INTO skills (id, name, category) VALUES (87, 'Vertex AI', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (88, 'Viem', 'DevOps');
INSERT INTO skills (id, name, category) VALUES (89, 'Vite', 'Tools');
INSERT INTO skills (id, name, category) VALUES (90, 'Vitest', 'Tools');
INSERT INTO skills (id, name, category) VALUES (91, 'Whisper.cpp', 'AI & Intelligence');
INSERT INTO skills (id, name, category) VALUES (92, 'pgvector', 'Databases');
INSERT INTO skills (id, name, category) VALUES (93, 'zkLogin', 'DevOps');

-- Insert Projects & Achievements
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (1, 'open-source', 'LLM-Wiki', 'Open Source AI Vault Sync', 'A local-first wiki that syncs Obsidian notes into a searchable knowledge graph.', 'https://github.com/ryanlau1220/llm-wiki', NULL, '/projects/llmwiki/screenshot.png', 1);
INSERT INTO project_achievements (project_id, content) VALUES (1, 'Orchestrated a TypeScript monorepo using Turborepo and Biome for linting, type-checking, and build caching.');
INSERT INTO project_achievements (project_id, content) VALUES (1, 'Designed a hybrid search RAG pipeline integrating Gemini and local Ollama models, optimizing context retrieval.');
INSERT INTO project_achievements (project_id, content) VALUES (1, 'Built a real-time markdown parser and file watcher synchronizing note vaults to PostgreSQL via Drizzle ORM.');
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 82);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 80);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 13);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 26);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 60);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 23);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 92);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 38);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 63);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 62);
INSERT INTO project_skills (project_id, skill_id) VALUES (1, 90);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (2, 'hackathon', 'LedgerTrace', 'AI Marathon 2026', 'An async reconciliation engine for Stripe and TRON payment events.', 'https://github.com/ryanlau1220/LedgerTrace', 'https://youtu.be/1o_8vI79uZQ', '/projects/aimarathon/screenshot.png', 2);
INSERT INTO project_achievements (project_id, content) VALUES (2, 'Developed an asynchronous middleware pipeline using Redis to ingest payment events with real-time FX enrichment.');
INSERT INTO project_achievements (project_id, content) VALUES (2, 'Deployed secure policy-gating using Trusted Execution Environments (TEE) to validate inbound payloads.');
INSERT INTO project_achievements (project_id, content) VALUES (2, 'Integrated deterministic gating to post validated transactions to a Blnk double-entry ledger database.');
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 58);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 27);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 66);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 72);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 12);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 22);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 11);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 77);
INSERT INTO project_skills (project_id, skill_id) VALUES (2, 79);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (3, 'hackathon', 'WarungAI', 'UMHackathon 2026', 'A voice assistant for micro-SMEs to manage orders and stock.', 'https://github.com/ryanlau1220/UMHackathon-WarungAI', 'https://youtu.be/B28F81tFSwQ', '/projects/umhackathon/screenshot.png', 3);
INSERT INTO project_achievements (project_id, content) VALUES (3, 'Constructed local speech transcription handlers using open LLM sound models.');
INSERT INTO project_achievements (project_id, content) VALUES (3, 'Designed relational structures in PostgreSQL to log incoming customer orders.');
INSERT INTO project_achievements (project_id, content) VALUES (3, 'Created dashboard for micro-stall merchants to monitor revenue in real-time.');
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 86);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 46);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 92);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 12);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 21);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 83);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 48);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 35);
INSERT INTO project_skills (project_id, skill_id) VALUES (3, 91);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (4, 'hackathon', 'AEGIS', 'MyAI Future Hackathon 2026', 'An offline-first disaster relief platform for flood response.', 'https://github.com/ryanlau1220/MyAI_Future_Hackathon-AEGIS', 'https://youtu.be/WdT77Km9cOc', '/projects/myaifuture/screenshot.png', 4);
INSERT INTO project_achievements (project_id, content) VALUES (4, 'Integrated OpenCV pipelines to analyze frame feeds and overlay bounding boxes.');
INSERT INTO project_achievements (project_id, content) VALUES (4, 'Engineered Redis queuing to process safety alerts without blocking video feeds.');
INSERT INTO project_achievements (project_id, content) VALUES (4, 'Configured multi-container Docker compose environments for local edge node testing.');
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 58);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 80);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 33);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 81);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 55);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 27);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 67);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 65);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 30);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 38);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 54);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 51);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 74);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 75);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 56);
INSERT INTO project_skills (project_id, skill_id) VALUES (4, 20);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (5, 'hackathon', 'Shelf OS', 'KitaHack 2026', 'An AI retail system for shelf auditing and waste reduction.', 'https://github.com/ryanlau1220/KitaHack_Shelf-OS', 'https://youtu.be/ZXsvXQVFl1M', '/projects/kitahack/screenshot.png', 5);
INSERT INTO project_achievements (project_id, content) VALUES (5, 'Developed server handlers to trace device heartbeats and shelf load capacities.');
INSERT INTO project_achievements (project_id, content) VALUES (5, 'Designed local database schemas using SQLite to manage instant item records.');
INSERT INTO project_achievements (project_id, content) VALUES (5, 'Crafted responsive layout displaying active warning states for low-stock shelves.');
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 19);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 32);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 29);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 31);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 69);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 87);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 38);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 17);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 16);
INSERT INTO project_skills (project_id, skill_id) VALUES (5, 42);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (6, 'hackathon', 'AI Powered Learning Companion', 'Great Malaysia AI Hackathon 2025', 'An AI study companion that turns text into flashcards, summaries, and schedules.', 'https://github.com/ryanlau1220/GreatMalaysiaAIHackathon_AI-Powered-Learning-Companion', 'https://youtu.be/DEYFJtiCJsI', '/projects/greatmalaysiaai/screenshot.png', 6);
INSERT INTO project_achievements (project_id, content) VALUES (6, 'Constructed text parsing logic to decompose syllabus contents into semantic chunks.');
INSERT INTO project_achievements (project_id, content) VALUES (6, 'Engineered LLM prompts to extract key educational takeaways and format flashcards.');
INSERT INTO project_achievements (project_id, content) VALUES (6, 'Implemented dashboard to track student study history and recall metrics.');
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 71);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 89);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 80);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 27);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 3);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 4);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 7);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 6);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 5);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 24);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 21);
INSERT INTO project_skills (project_id, skill_id) VALUES (6, 1);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (7, 'hackathon', 'EcoChain', 'DevMatch Hackathon 2025', 'A blockchain app for tracking environmental data and carbon credits.', 'https://github.com/ryanlau1220/DevMatch-EcoChain', 'https://youtu.be/XhHIwUfuJPs', '/projects/devmatch/screenshot.png', 7);
INSERT INTO project_achievements (project_id, content) VALUES (7, 'Designed EVM smart contracts in Solidity for tracking offset credits and verifying green compliance.');
INSERT INTO project_achievements (project_id, content) VALUES (7, 'Built a NextJS web dashboard showing real-time carbon statistics and transaction history.');
INSERT INTO project_achievements (project_id, content) VALUES (7, 'Integrated Web3 wallet connections to manage carbon credit assets securely.');
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 71);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 89);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 80);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 78);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 93);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 76);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 45);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 84);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 61);
INSERT INTO project_skills (project_id, skill_id) VALUES (7, 38);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (8, 'hackathon', 'Fake Review and Fraud Detection', 'FutureHack 2025', 'A fake review detector using NLP and behavioral fraud signals.', 'https://github.com/ryanlau1220/FutureHack_Fake-Review-and-Fraud-Detection', NULL, '/projects/futurehack/screenshot.png', 8);
INSERT INTO project_achievements (project_id, content) VALUES (8, 'Created review classification algorithms in Python using NLP sentiment scoring.');
INSERT INTO project_achievements (project_id, content) VALUES (8, 'Conducted regression and cluster analysis in R to model merchant risk scores.');
INSERT INTO project_achievements (project_id, content) VALUES (8, 'Designed transactional audit schemas in PostgreSQL to flag anomalies.');
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 69);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 28);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 68);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 47);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 9);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 44);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 15);
INSERT INTO project_skills (project_id, skill_id) VALUES (8, 50);
INSERT INTO projects (id, category, title, subtitle, description, github_url, video_url, image_url, sort_order) VALUES (9, 'internship', 'KrypitalX', 'Centralized Trading Platform', 'A crypto exchange platform for wallet flows, compliance checks, and live account updates.', NULL, NULL, NULL, 9);
INSERT INTO project_achievements (project_id, content) VALUES (9, 'Owned the end-to-end design of centralized exchange backend services in Go, implementing compliant wallet flows.');
INSERT INTO project_achievements (project_id, content) VALUES (9, 'Spearheaded real-time event pipeline integrations using Redis Pub/Sub to trigger instant frontend state updates.');
INSERT INTO project_achievements (project_id, content) VALUES (9, 'Centralized IAM and user authentication infrastructure utilizing Keycloak for standard OIDC protocols.');
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 41);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 71);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 89);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 80);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 73);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 81);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 33);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 37);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 53);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 2);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 77);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 88);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 72);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 66);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 36);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 21);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 40);
INSERT INTO project_skills (project_id, skill_id) VALUES (9, 8);

-- Insert Timeline Items
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (1, 'BS in Software Engineering', 'Asia Pacific University (APU)', 'Feb 2026 – Present', 'Pursuing advanced software engineering studies focusing on architecture and distributed databases.', 'education', NULL, 202602, 0);
INSERT INTO timeline_achievements (timeline_id, content) VALUES (1, 'Deepening core engineering concepts in distributed ledger databases.');
INSERT INTO timeline_achievements (timeline_id, content) VALUES (1, 'Analyzing network protocols and low-latency system architectures.');
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (1, 70);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (1, 25);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (2, 'Software Engineer Intern', 'First Pavilion Technology Sdn Bhd', 'Sept 2025 – Jan 2026', 'Owned centralized exchange wallet development, Keycloak IAM integration, and Docker CI/CD pipelines.', 'internship', NULL, 202509, 0);
INSERT INTO timeline_achievements (timeline_id, content) VALUES (2, 'Designed centralized backend wallet services and tiered compliance checks.');
INSERT INTO timeline_achievements (timeline_id, content) VALUES (2, 'Built Redis event notifications to synchronize client frontend state changes.');
INSERT INTO timeline_achievements (timeline_id, content) VALUES (2, 'Managed database migrations and automated deployment workflows via GitHub Actions.');
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 41);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 72);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 21);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 39);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 52);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 53);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (2, 76);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (3, 'Diploma in ICT', 'Asia Pacific University (APU)', 'Aug 2023 – Aug 2025', 'Completed core software foundations, object-oriented programming, and relational databases.', 'education', NULL, 202308, 0);
INSERT INTO timeline_achievements (timeline_id, content) VALUES (3, 'Graduated with a CGPA of 3.56 / 4.0.');
INSERT INTO timeline_achievements (timeline_id, content) VALUES (3, 'Built relational database projects and basic security models.');
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 32);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 49);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 69);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 57);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 43);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 64);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 14);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (3, 50);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (4, 'LedgerTrace', 'AI Marathon 2026', 'May 2026', 'Designed asynchronous double-entry analytical ledgers and Stripe/TRON webhook processing.', 'hackathon', NULL, 202605, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (4, 13);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (4, 85);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (4, 11);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (4, 77);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (4, 79);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (4, 59);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (5, 'Warung AI', 'UMHackathon 2026', 'Apr 2026', 'Developed an AI conversational merchant voice assistant to automate order tracking and inventory forecasting.', 'hackathon', NULL, 202604, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 83);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 46);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 92);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 91);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 63);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 48);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 12);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (5, 18);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (6, 'AEGIS', 'MyAI Future Hackathon 2026', 'Apr 2026', 'Co-created a computer vision safety monitoring system integrated with local LLMs to flag compliance risks.', 'hackathon', NULL, 202604, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 54);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 51);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 65);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 67);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 30);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 56);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (6, 10);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (7, 'Fake Review and Fraud Detection', 'FutureHack 2025', 'Jul 2025', 'Created NLP sentiment review detection models and transactional outlier regression scoring.', 'hackathon', NULL, 202507, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (7, 69);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (7, 9);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (7, 43);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (8, 'EcoChain', 'DevMatch Hackathon 2025', 'Aug 2025', 'Authored EVM carbon credit offsets tracking smart contracts in Solidity and NextJS Web3 controls.', 'hackathon', NULL, 202508, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (8, 76);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (8, 58);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (8, 78);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (8, 45);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (8, 84);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (8, 61);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (9, 'AI-Powered Learning Companion', 'Great Malaysia AI Hackathon 2025', 'Sep 2025', 'Designed LLM parsing algorithms and adaptive retrieval prompts for personalized flashcard generation.', 'hackathon', NULL, 202509, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (9, 3);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (9, 4);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (9, 7);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (9, 71);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (9, 21);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (9, 1);
INSERT INTO timeline (id, title, subtitle, date_display, description, category, outcome, sort_key, is_featured) VALUES (10, 'Shelf OS', 'KitaHack 2026', 'Feb 2026', 'Built a local inventory shelf tracker with device heartbeat statuses and SQLite warning flags.', 'hackathon', NULL, 202602, 1);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (10, 32);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (10, 87);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (10, 34);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (10, 29);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (10, 16);
INSERT INTO timeline_skills (timeline_id, skill_id) VALUES (10, 31);